name: Docker Build Job

on:
  workflow_call:

jobs:
  docker_builds:
    name: ${{ matrix.command_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - command_name: "controller"
            cmd_path_prefix: cmd
          - command_name: "extproc"
            cmd_path_prefix: cmd
          - command_name: "aigw"
            cmd_path_prefix: cmd
          - command_name: "testupstream"
            cmd_path_prefix: tests/internal/testupstreamlib
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v5
        with:
          cache: false
          go-version-file: go.mod
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v4
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
            ~/go/bin
          key: build-container-${{ hashFiles('**/go.mod', '**/go.sum', '**/Makefile') }}

      - uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

      - name: Login into DockerHub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Push images for the push events, e.g. when a new tag is pushed as well as PR merges.
      # * Only use the tag if the event is a tag event, otherwise use the hash.
      # * Build for both amd64 and arm64 platforms.
      - name: Build and Push Image
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="${{ github.sha }}"
          fi
          make docker-build.${{ matrix.command_name }} CMD_PATH_PREFIX=${{ matrix.cmd_path_prefix }} ENABLE_MULTI_PLATFORMS=true TAG=$TAG DOCKER_BUILD_ARGS="--push"

      - name: Build and Push Image Latest
        run: |
          if [[ "$GITHUB_REF" != refs/tags/* ]]; then
            make docker-build.${{ matrix.command_name }} CMD_PATH_PREFIX=${{ matrix.cmd_path_prefix }} ENABLE_MULTI_PLATFORMS=true TAG="latest" DOCKER_BUILD_ARGS="--push"
          fi
